model:
  image_size: 128
  in_image_depth: 3
  nb_blocks: 4
  block_type: "resnet"
  padding: "SAME"
  nb_initial_filters: 64
  initializer: "he_normal"
  use_batchnorm: true
  use_dropout: false

training:
  batch_size: 8
  learning_rate: 1e-4
  num_epochs: 1
  checkpoint_dir: "./checkpoints"
  checkpoint_name: "ckpt-1"
  log_dir: "../logs"

dataset:
  labelmap_path: "./data/pascalvoc/labelmap.json"
  colormap_path: "./data/pascalvoc/colormap.json"
  train_image_path: "./data/pascalvoc/train_image_paths.txt"
  train_mask_path: "./data/pascalvoc/train_mask_paths.txt"
  test_image_path: "./data/pascalvoc/val_image_paths.txt"
  test_mask_path: "./data/pascalvoc/val_mask_paths.txt"
  test_image: ""