model:
  image_size: 256
  in_image_depth: 3
  nb_blocks: 4
  block_type: "basic"
  padding: "SAME"
  nb_initial_filters: 64
  initializer: "he_normal"
  use_batchnorm: true
  use_dropout: false

training:
  batch_size: 8
  learning_rate: 1e-4
  num_epochs: 10
  checkpoint_dir: "../checkpoints"
  log_dir: "../logs"

dataset:
  labelmap_path: "./data/labelmap.json"
  train_image_path: "./data/image_paths.txt"
  train_mask_path: "./data/mask_paths.txt"