model:
  in_image_depth: 3
  nb_classes: 10
  nb_blocks: 4
  block_type: "basic"
  padding: "SAME"
  nb_initial_filters: 64
  initializer: "he_normal"
  use_batchnorm: true
  use_dropout: false

training:
  batch_size: 8
  learning_rate: 1e-4
  num_epochs: 10

dataset:
  train_path: "data/train"
  test_path: "data/test"